apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

namespace: example
namePrefix: example-

secretGenerator:
  - name: postgres-secret
    behavior: replace
    literals:
      - POSTGRES_PASSWORD=example-password

images:
  - name: postgres
    newTag: 18.1-alpine

patches:
  - path: postgres-storage-patch.yaml
