#apiVersion: kustomize.config.k8s.io/v1
#kind: Kustomization

# you can also manage namespace, commonLabels, etc.
namespace: default

resources:
  - postgres-stateful.yaml

# optionally, you can declare vars or use secretGenerator
secretGenerator:
  - name: postgres-secret
    literals:
      #- POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      #- POSTGRES_DB=database
    type: Opaque

images:
    - name: postgres
      newTag: 18.1-alpine

generatorOptions:
  disableNameSuffixHash: true
